package com.hosannasolutions.solisla.audit;

public enum AuditAction {
    USER_LOGIN_SUCCEEDED,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_ARCHIVED,
    INVENTORY_ADJUSTED,
    ORDER_CREATED,
    ORDER_STATUS_CHANGED,
    ORDER_CANCELLED,
    PAYMENT_STATUS_CHANGED,
    WHATSAPP_MESSAGE_QUEUED,
    WHATSAPP_MESSAGE_SENT,
    WHATSAPP_MESSAGE_FAILED
}
